site_name: IDendro
theme:
  name: "material"
  highlightjs: true
  pygments: true
  icon:
    admonition:
      tip: octicons/squirrel-16
  hljs_languages:
    - python

plugins:
  - mkdocstrings
  - mkdocs-jupyter:     
      execute: true
      remove_tag_config:
        remove_input_tags:
          - remove


nav:
  - Home page: index.md  
  - How-To Guides:
    - Getting started: getting-started.md
    - Customizing looks:
      - custom-colors.ipynb
      - custom-labels.ipynb
      - custom-attributes.ipynb
      - rotating.ipynb
    - Using in Streamlit: streamlit.md
  - Reference:
    - Creating dendrogram objects: reference.md
    - Plotting dendrograms: dendrogram.md
    - Callback functions for formatting: callbacks.md
    - Clustering Info Container: cluster-info-container.md
    - Data Containers: data_containers.md
    

watch:
  - idendro