site_name: IDendro
theme:
  name: "material"
  highlightjs: true
  pygments: true
  icon:
    admonition:
      tip: octicons/squirrel-16
  hljs_languages:
    - python

plugins:
  - mkdocstrings
  - mkdocs-jupyter:     
      execute: true      
      remove_tag_config:
        remove_input_tags:
          - remove


nav:
  - Home page: index.ipynb    
  - Getting started: 
    - guides/clustering-library-integration.ipynb
    - guides/visualization-library-integration.ipynb
  - Customizing looks:
    - guides/custom-colors.ipynb
    - guides/custom-labels.ipynb
    - guides/custom-attributes.ipynb
    - guides/rotating.ipynb
  - Using in Streamlit: streamlit.md
  - API Reference:
    - Creating dendrogram objects: reference/reference.md
    - Plotting dendrograms: reference/dendrogram.md
    - Callback functions for formatting: reference/callbacks.md
    - Clustering Info Container: reference/cluster-info-container.md
    - Data Containers: reference/data_containers.md
  - Case studies:
    - Signal anomaly detection: case-studies/signal-demo.ipynb
    

watch:
  - idendro

extra_css:
  - css/custom.css