site_name: IDendro
theme:
  name: "material"
  custom_dir: docs/overrides
  highlightjs: true
  pygments: true
  icon:
    admonition:
      tip: octicons/squirrel-16
  hljs_languages:
    - python
  features:
    - content.action.edit
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections

repo_url: https://github.com/kamicollo/idendro
edit_uri: edit/main/docs/
repo_name: kamicollo/idendro

plugins:
  - mkdocstrings
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - mkdocs-jupyter:     
      execute: true      
      remove_tag_config:
        remove_input_tags:
          - remove


nav:
  - Getting Started: 
    - IDendro 101: index.ipynb      
    - Clustering library integration: guides/clustering-library-integration.ipynb
    - Visualization library integration: guides/visualization-library-integration.ipynb
  - Customizing looks:
    - guides/custom-colors.ipynb
    - guides/custom-labels.ipynb
    - guides/custom-attributes.ipynb
    - guides/rotating.ipynb
  - Using in Streamlit: streamlit.md
  - API Reference:
    - Creating dendrogram objects: reference/reference.md
    - Plotting dendrograms: reference/dendrogram.md
    - Callback functions for formatting: reference/callbacks.md
    - Clustering Info Container: reference/cluster-info-container.md
    - Data Containers: reference/data_containers.md
  - Case studies:
    - Signal anomaly detection: case-studies/signal-demo.ipynb
    

watch:
  - idendro

hooks:
  - docs/plotly_fix.py

extra:
  social:
    - icon: fontawesome/solid/signature
      link: https://aurimas.eu